M48
; DRILL file {KiCad 7.0.10} date Friday, April 05, 2024 at 10:32:12 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-05T22:32:12-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X113.97Y-97.46
X115.24Y-49.2
X166.04Y-64.44
X166.04Y-92.38
M30
